export default {
  TOGGLE_LOADER: "TOGGLE_LOADER",
  TOGGLE_LOADER_TWO: "TOGGLE_LOADER_TWO",
  DRAWER: "DRAWER",
  SHOW_DIALOG: "SHOW_DIALOG",
  DAY_OFFS: "DAY_OFFS",
  ORDERS: "ORDERS",
  ORDERS_INFO: "ORDERS_INFO",
  PAYMENT_STATUS: "PAYMENT_STATUS"
};
